"""Eaglercraft server and WSS proxy management."""

from __future__ import annotations

import asyncio
import json
import shutil
from pathlib import Path
from typing import Optional

import httpx

from blocklaunch.config import BlockLaunchSettings
from blocklaunch.utils.logging import setup_logging

logger = setup_logging(name="blocklaunch.eaglercraft")


class EaglercraftManager:
    """Manages Eaglercraft server setup and WSS proxy."""

    EAGLERCRAFT_REPO = "Eaglercraft-X-Reborn"
    EAGLERCRAFT_XBUKKIT_URL = (
        "https://github.com/Eaglercraft-X-Reborn/EaglercraftXBungee/releases/latest/download/"
        "EaglercraftXBungee.jar"
    )
    EAGLERCRAFT_XSERVER_URL = (
        "https://github.com/Eaglercraft-X-Reborn/EaglercraftXServer/releases/latest/download/"
        "EaglercraftXServer.jar"
    )
    EAGLERCRAFT_EPLUGINS_URL = (
        "https://github.com/Eaglercraft-X-Reborn/EaglercraftXEPlugins/releases/latest/download/"
        "EaglercraftXEPlugins.jar"
    )

    def __init__(self, settings: BlockLaunchSettings) -> None:
        self.settings = settings
        self.client = httpx.AsyncClient(
            timeout=120.0,
            follow_redirects=True,
            headers={"User-Agent": "BlockLaunch/1.0"},
        )

    async def close(self) -> None:
        await self.client.aclose()

    async def setup_eaglercraft(self, server_dir: Path, wss_port: int = 8081) -> dict:
        """Set up Eaglercraft support for a server.

        This installs:
        1. EaglercraftXServer plugin (for the backend server)
        2. EaglercraftXBungee (WebSocket proxy that browsers connect to)
        3. Configuration for the WSS proxy

        Returns dict with setup info.
        """
        server_dir.mkdir(parents=True, exist_ok=True)
        plugins_dir = server_dir / "plugins"
        plugins_dir.mkdir(parents=True, exist_ok=True)

        results = {
            "server_plugin": None,
            "bungee_jar": None,
            "wss_config": None,
            "errors": [],
        }

        # Download EaglercraftXServer plugin
        try:
            logger.info("Downloading EaglercraftXServer plugin...")
            plugin_path = plugins_dir / "EaglercraftXServer.jar"
            await self._download_jar(self.EAGLERCRAFT_XSERVER_URL, plugin_path)
            results["server_plugin"] = str(plugin_path)
        except Exception as e:
            logger.error(f"Failed to download EaglercraftXServer: {e}")
            results["errors"].append(f"EaglercraftXServer download failed: {e}")

        # Download EaglercraftXEPlugins (additional eaglercraft plugins)
        try:
            logger.info("Downloading EaglercraftXEPlugins...")
            eplugins_path = plugins_dir / "EaglercraftXEPlugins.jar"
            await self._download_jar(self.EAGLERCRAFT_EPLUGINS_URL, eplugins_path)
        except Exception as e:
            logger.warning(f"Failed to download EaglercraftXEPlugins (non-critical): {e}")

        # Set up EaglercraftXBungee (WSS proxy)
        bungee_dir = server_dir / "eaglercraft-bungee"
        bungee_dir.mkdir(parents=True, exist_ok=True)

        try:
            logger.info("Downloading EaglercraftXBungee...")
            bungee_jar = bungee_dir / "EaglercraftXBungee.jar"
            await self._download_jar(self.EAGLERCRAFT_XBUKKIT_URL, bungee_jar)
            results["bungee_jar"] = str(bungee_jar)
        except Exception as e:
            logger.error(f"Failed to download EaglercraftXBungee: {e}")
            results["errors"].append(f"EaglercraftXBungee download failed: {e}")

        # Create BungeeCord config
        config_path = bungee_dir / "config.yml"
        self._create_bungee_config(config_path, wss_port)
        results["wss_config"] = str(config_path)

        # Create listener config for Eaglercraft
        listener_dir = plugins_dir / "EaglercraftXServer"
        listener_dir.mkdir(parents=True, exist_ok=True)
        self._create_listener_config(listener_dir, wss_port)

        return results

    def _create_bungee_config(self, config_path: Path, wss_port: int) -> None:
        """Create the BungeeCord configuration for Eaglercraft WSS proxy."""
        config = f"""# EaglercraftXBungee Configuration
# Generated by BlockLaunch

listeners:
- host: 0.0.0.0:{wss_port}
  motd: 'BlockLaunch Eaglercraft Server'
  max_players: 20
  tab_list: GLOBAL_PING
  force_default_server: false
  websocket: true
  server_names:
  - backend

servers:
  backend:
    address: localhost:25565
    restricted: false

groups:
  Admin:
  - admin
  - eaglercraft.command.*

permissions:
  default:
  - eaglercraft.command.list
  - eaglercraft.command.help
  admin:
  - eaglercraft.command.*
  - eaglercraft.command.op

prevent_proxy_connections: false
timeout: 30000
connection_throttle: 2000
log_commands: true
online_mode: false
"""
        config_path.write_text(config, encoding="utf-8")

    def _create_listener_config(self, listener_dir: Path, wss_port: int) -> None:
        """Create the EaglercraftXServer listener configuration."""
        config = {
            "listeners": [
                {
                    "host": f"0.0.0.0:{wss_port}",
                    "protocol": "websocket",
                    "allow_cookies": True,
                    "server_name": "BlockLaunch Eaglercraft",
                    "motd": "BlockLaunch Eaglercraft Server",
                    "max_players": 20,
                    "forward_ip": False,
                }
            ]
        }
        config_path_j = listener_dir / "listeners.json"
        config_path_j.write_text(json.dumps(config, indent=2), encoding="utf-8")

    async def start_wss_proxy(self, bungee_dir: Path, java_path: str, memory: str = "512M") -> asyncio.subprocess.Process:
        """Start the Eaglercraft WSS proxy (BungeeCord)."""
        bungee_jar = bungee_dir / "EaglercraftXBungee.jar"
        if not bungee_jar.exists():
            raise FileNotFoundError(f"EaglercraftXBungee.jar not found at {bungee_jar}")

        process = await asyncio.create_subprocess_exec(
            java_path,
            f"-Xmx{memory}",
            "-Xms128M",
            "-jar",
            str(bungee_jar),
            cwd=str(bungee_dir),
            stdin=asyncio.subprocess.PIPE,
            stdout=asyncio.subprocess.PIPE,
            stderr=asyncio.subprocess.STDOUT,
        )

        logger.info(f"Started Eaglercraft WSS proxy (PID: {process.pid})")
        return process

    async def _download_jar(self, url: str, target: Path) -> None:
        """Download a JAR file."""
        resp = await self.client.get(url)
        resp.raise_for_status()
        target.write_bytes(resp.content)
        logger.info(f"Downloaded {target.name} ({len(resp.content) / 1024 / 1024:.1f} MB)")

    async def get_eaglercraft_client_html(self, server_name: str, wss_url: str) -> str:
        """Generate a simple HTML page that loads the Eaglercraft client and connects to the server."""
        return f"""<!DOCTYPE html>
<html>
<head>
    <title>Eaglercraft - {server_name}</title>
    <style>
        body {{ margin: 0; background: #000; overflow: hidden; }}
        #game-container {{ width: 100vw; height: 100vh; }}
    </style>
</head>
<body>
    <div id="game-container"></div>
    <script>
        // Eaglercraft client configuration
        window.eaglercraftConfig = {{
            server: '{wss_url}',
            name: '{server_name}'
        }};
    </script>
    <p>Connect to your Eaglercraft server at: <code>{wss_url}</code></p>
    <p>You need an Eaglercraft client to connect. Use the Eaglercraft client at
    <a href="https://eaglercraft.com">eaglercraft.com</a> and connect to the above WSS URL.</p>
</body>
</html>
"""
